### ISSUE TITLE
次元城(ciyuancheng)规则与自己的规则无法使用

### ISSUE THREAD

**Issue by ymqng** [Predidit/KazumiRules#13]
## 演示视频

https://github.com/user-attachments/assets/e7235c3e-5de5-4599-8238-88b847170298

次元城的王站可以进去，也可以正常观看视频。但在软件内使用从仓库导入的规则，则无法正常观看。

***

另一个是我自己做的规则，网站:https://9ciyuan.com

我知道可能不是软件本身的问题，我自己也是从头开始学了很久，单纯就是想用这个软件看“囧次元”的番。但自己捣鼓了好几个小时，最后发现无法播放视频，但原网站都一切正常。想知道是不是我自己的问题。

规则链接:kazumi://eyJhcGkiOiIxIiwidHlwZSI6IjEiLCJuYW1lIjoiOWNpeXVhbiIsInZlcnNpb24iOiIxLjAiLCJtdWxpU291cmNlcyI6dHJ1ZSwidXNlV2VidmlldyI6dHJ1ZSwidXNlTmF0aXZlUGxheWVyIjp0cnVlLCJ1c2VyQWdlbnQiOiIiLCJiYXNlVVJMIjoiaHR0cHM6Ly85Y2l5dWFuLmNvbSIsInNlYXJjaFVSTCI6Imh0dHBzOi8vOWNpeXVhbi5jb20vaW5kZXgucGhwL3ZvZC9zZWFyY2guaHRtbD93ZD1Aa2V5d29yZCIsInNlYXJjaExpc3QiOiIvL2Rpdls0XS9kaXYiLCJzZWFyY2hOYW1lIjoiLy9kaXZbMl0vaDMiLCJzZWFyY2hSZXN1bHQiOiIvL2RpdlsyXS9oMy9hIiwiY2hhcHRlclJvYWRzIjoiLy9kaXZbNF0vZGl2WzJdL2RpdlsxXS9kaXZbMV0vZGl2WzJdLy91bCIsImNoYXB0ZXJSZXN1bHQiOiIvL2xpL2EifQ==

###上述操作均未使用梯子

**Comment by Predidit** [comment]
看日志似乎是解析器内部的问题，晚些时候我会尝试修复。

**Comment by ymqng** [comment]
> 看日志似乎是解析器内部的问题，晚些时候我会尝试修复。

加油₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by Predidit** [comment]
我想我已经把这个问题修好了。

等待下一个版本发布，应该是明天。

**Comment by ymqng** [comment]
> 我想我已经把这个问题修好了。
> 
> 等待下一个版本发布，应该是明天。

速度好快啊，已经迫不及待了。

**Comment by Predidit** [comment]
1.2.2 已经发布
