### ISSUE TITLE
[question] 稀饭动画链接跳转问题

### ISSUE THREAD

**Issue by LaolunsiG** [Predidit/KazumiRules#19]
# 稀饭动画链接跳转问题
[稀饭动画](https://dick.xfani.com/watch/394/1/1.html)，这个动画在 web 是可以正常播放的。

\# JSON 配置
```
{
    "api": "1",
    "type": "anime",
    "name": "dick_xfani",
    "version": "1.0",
    "muliSources": true,
    "useWebview": true,
    "useNativePlayer": true,
    "userAgent": "",
    "baseURL": "https://dick.xfani.com/",
    "searchURL": "https://dick.xfani.com/search.html?wd=@keyword",
    "searchList": "//div[4]/div/div[1]/div/div",
    "searchName": "//div[3]/div[1]/div[1]",
    "searchResult": "//div[3]/div[2]/a[1]",
    "chapterRoads": "//div[6]/div[2]/div",
    "chapterResult": "//div/div/ul/li/a"
}
```

## 这个动画出现了链接跳转，好像会导致 kazumi 无法正常播放。
![Snipaste_2024-08-18_15-48-21](https://github.com/user-attachments/assets/1a031fe1-df32-4593-b8b7-8b3eb41a7e48)

## kazumi 确实获取到视频链接，但是无法播放
![Snipaste_2024-08-18_15-49-08](https://github.com/user-attachments/assets/85d27b81-397a-43c5-a798-df4a27233cfd)

### 会一直在这个界面
![Snipaste_2024-08-18_15-49-14](https://github.com/user-attachments/assets/30d49918-49e9-4fa8-b53d-e7ad44e29eac)

##  而没有进行跳转的 [keai.](https://keai.cm/?id=60493&t=19&a=1&pg=2) 可以正常播放。

#问题

**Comment by Predidit** [comment]
暂时没有解决方法，这个问题涉及CORS。

android webview / Apple WKwebview / Microsoft webview2 均不支持禁用 CORS。理论上这只能在 Linux 上实现，但这会导致 Linux 版本和其他版本的行为不一致。

另一个可能的解决方案是使用 CEF 。但这需要打包一个 Chromium 内核，大概会让安装包体积膨胀约 150M

**Comment by Predidit** [comment]
话说您有兴趣成为规则仓库的协作者吗。

这将允许您自行合并自己的PR，并审核与合并其他贡献者的PR。

**Comment by LaolunsiG** [comment]
> 话说您有兴趣成为规则仓库的协作者吗。
> 
> 这将允许您自行合并自己的PR，并审核与合并其他贡献者的PR。

我感兴趣

但是，我对 github 的功能认知还不完善（正在学习），只会一些普通的操作，可能会造成困扰。

而且，我只有在没事的时候，才会的做一些规则

**Comment by LaolunsiG** [comment]
> 暂时没有解决方法，这个问题涉及CORS。
> 
> android webview / Apple WKwebview / Microsoft webview2 均不支持禁用 CORS。理论上这只能在 Linux 上实现，但这会导致 Linux 版本和其他版本的行为不一致。
> 
> 另一个可能的解决方案是使用 CEF 。但这需要打包一个 Chromium 内核，大概会让安装包体积膨胀约 150M

好的谢谢了。

**Comment by Predidit** [comment]
我已经向您发送了协作者邀请。包括您的PR在内，我希望您可以优先等待我的处理，当我忙于其他事情，24小时没有处理PR时，您可以自行决定如何处理PR。

**Comment by Predidit** [comment]
xfdm 的问题在 1.3.6 可以通过启用简易解析修复
