### ISSUE TITLE
[請求] 以Anime1.me作為提供者？

### ISSUE THREAD

**Issue by ElliotCHEN37** [Predidit/KazumiRules#21]
有看到你的另外一個項目oneAnime, 但還是希望可以新增一個Anime1.me的規則

今天有嘗試過寫一個規則，但有點不太懂（重點：沒成功），希望可以完善文檔

**Comment by Predidit** [comment]
Anime1 的架构是我见过的所有视频网站中最古怪的

看上去它是基于 wordpress(一个流行的博客程序) 魔改的

所以他的行为和正常视频网站差异非常非常大，目前kazumi支持不了
