### ISSUE TITLE
软件里规则仓库没有这里的多啊

### ISSUE THREAD

**Issue by tfgc51379** [Predidit/KazumiRules#28]

**Comment by Predidit** [comment]
这里有已经被移除和禁用的规则

**Comment by hanny0** [comment]
> 这里有已经被移除和禁用的规则

请问应该怎么在kazumi导入这里的规则?从剪贴版导入直接复制该仓库的链接给他无效，选择从规则仓库导入的话只有镜像，里面的规则确实没有这里多，现在的kazumi内部自带的规则仓库里面的规则，是就是这个项目里面所有能用的吗，其余的规则都是被移除或失效一类的吗
