### ISSUE TITLE
ez 站的番剧chapter 的位置索引和集数恰好相反，且备用源也被检索

### ISSUE THREAD

**Issue by PaRr0tBoY** [Predidit/KazumiRules#29]
<img width="1540" alt="image" src="https://github.com/user-attachments/assets/d7b23d0a-02e6-4423-86a7-5f5ee6ab620d">

/html/body/div[4]/section[1]/a[20] //这是某番剧在该网站的备用源，但是和主源在同一页
/html/body/div[4]/section[1]/a[4] //这是某番剧的第 8 集，因为是从第 11 集开始索引的

因为备用源和主源在同一页，所以会检索出来比实际集数要多的chapter，且索引是倒置的，想问下有办法解决吗？

网站是 https://www.ezdmw.site/Index/bangumi/83113.html

规则：kazumi://eyJhcGkiOiIxIiwidHlwZSI6IjEiLCJuYW1lIjoiRXoiLCJ2ZXJzaW9uIjoiMC4xIiwibXVsaVNvdXJjZXMiOnRydWUsInVzZVdlYnZpZXciOnRydWUsInVzZU5hdGl2ZVBsYXllciI6dHJ1ZSwidXNlUG9zdCI6ZmFsc2UsInVzZXJBZ2VudCI6IiIsImJhc2VVUkwiOiJodHRwczovL3d3dy5lemRtdy5zaXRlLyIsInNlYXJjaFVSTCI6Imh0dHBzOi8vd3d3LmV6ZG13LnNpdGUvSW5kZXgvc2VhcmNoLmh0bWw/c2VhcmNoVGV4dD1Aa2V5d29yZCIsInNlYXJjaExpc3QiOiIvL3NlY3Rpb24vc2VjdGlvbi9kaXYiLCJzZWFyY2hOYW1lIjoiLy9wL3NwYW4vdGV4dCgpIiwic2VhcmNoUmVzdWx0IjoiLy9hIiwiY2hhcHRlclJvYWRzIjoiLy9kaXZbNF0vc2VjdGlvblsxXSIsImNoYXB0ZXJSZXN1bHQiOiIvL2EifQ==

**Comment by Predidit** [comment]
倒序的问题没有暂时没有办法解决

将备用源视为更多的剧集，在这个网页的布局下也没有太好的解决方法，看上去可以通过指定 <a> 标签对应的 class 字段来只选择主要播放源

**Comment by PaRr0tBoY** [comment]
好的我再试试

**Comment by Predidit** [comment]
索引倒置的问题应该在 1.3.9 得到解决
