### ISSUE TITLE
找到一个比仓库里的次元域资源更多一点的次元域

### ISSUE THREAD

**Issue by XHXYT** [Predidit/KazumiRules#40]
但是不知道要咋写才能进入视频详情页，试了好几种方法也没搞好
kazumi://eyJhcGkiOiIxIiwidHlwZSI6IjEiLCJuYW1lIjoiQ2l5dWFueXUiLCJ2ZXJzaW9uIjoiMS4wIiwibXVsaVNvdXJjZXMiOnRydWUsInVzZVdlYnZpZXciOnRydWUsInVzZU5hdGl2ZVBsYXllciI6ZmFsc2UsInVzZVBvc3QiOmZhbHNlLCJ1c2VyQWdlbnQiOiIiLCJiYXNlVVJMIjoiaHR0cHM6Ly93d3cuY3ljZGguY2MiLCJzZWFyY2hVUkwiOiJodHRwczovL3d3dy5jeWNkaC5jYy9pbmRleC5waHAvdm9kL3NlYXJjaC5odG1sP3dkPUBrZXl3b3JkIiwic2VhcmNoTGlzdCI6Ii8vZGl2WzFdL2RpdlszXS9kaXYvZGl2L2RpdlsyXS9kaXYvL2RpdiIsInNlYXJjaE5hbWUiOiIvL2RpdlsyXS9kaXZbMV0vYS9zdHJvbmciLCJzZWFyY2hSZXN1bHQiOiIvL2FbMV0iLCJjaGFwdGVyUm9hZHMiOiIvL2Rpdi9kaXZbM10vZGl2L2RpdlsyXS8vZGl2IiwiY2hhcHRlclJlc3VsdCI6Ii8vZGl2WzJdL2Rpdi9kaXYvYSJ9

**Comment by Predidit** [comment]
这种仿冒站点不加。

它们的资源来源都是相同的，一个挂掉其他的也会挂掉。

而且他们的清晰度会比正主差很多，不少还有广告。
