### ISSUE TITLE
很多插件在android手机可以解析视频，但是在ipad上面解析不了视频，是苹果ios系统不支持吗？

### ISSUE THREAD

**Issue by simulationddln** [Predidit/KazumiRules#41]

**Comment by Predidit** [comment]
应该是 [Predidit/Kazumi#238](https://github.com/Predidit/Kazumi/issues/238)

尝试关闭硬件解码

**Comment by simulationddln** [comment]
谢谢您，我在想，应该不是ios系统屏蔽了吧？

**Comment by simulationddln** [comment]
感谢，我在iPad里面关闭了硬件解码，就能看视频了

**Comment by Predidit** [comment]
> 谢谢您，我在想，应该不是ios系统屏蔽了吧？

[Predidit/Kazumi#238](https://github.com/Predidit/Kazumi/issues/238) 里说过了啊

iOS 内嵌播放组件对 HEVC 格式的支持不完全。Apple 不是第一次这样破坏兼容性了, 可能他们认为以自己的影响力，可以倒逼开发者和标准制定者来让某个方案成为主流以结束相关领域的碎片化。但他们并不是总能成功。
