### ISSUE TITLE
关于平板适配的问题，设备vivopad1,iqoopad1

### ISSUE THREAD

**Issue by chiyuanQAQxianren** [Predidit/KazumiRules#5]
使用平板打开后无法链接网络，一直提示链接超时
![Screenshot_20240701_231220](https://github.com/Predidit/KazumiRules/assets/106142215/f0982d2d-3870-47e1-a6b9-24e6e4743ba6)

**Comment by Predidit** [comment]
不要规则仓库开关于app本体的issue。

网络请求的封装是统一的，和具体平台无关。

看上去是你的代理服务的IP同时被太多人使用而被bangumi拉黑了。也许不用代理好一点。
