### ISSUE TITLE
蜜糖(mitang)，萌番(mengfan)，eacg源无法使用

### ISSUE THREAD

**Issue by humosu** [Predidit/KazumiRules#6]
可能是进入网站要人机验证，现在无法使用
eacg什么问题看下面图片（位置：山西）
![Screenshot_20240708_151627_com microsoft emmx](https://github.com/Predidit/KazumiRules/assets/99652521/445534a4-9f05-4ae7-bc4a-23370ed77a0d)
实际上萌番是改版以前的蜜糖，按理萌番网站已经弃用了，但好像被人搞复活了，视频源还是蜜糖的，但是加了广告

**Comment by Predidit** [comment]
我这边测试都没有问题。

梯子关了试试？这些站点基本都对来自中国之外地区的访问要求验证码。

**Comment by humosu** [comment]
测试eacg时使用了梯子，但依旧被拦截，萌番和蜜糖是验证问题，和挂不挂没关系，可能和我在的地区有关，我不能测试中国别的地区或其他运营商网络的链接情况，对于山西，这几个是不可用的发自我的手机-------- 原始邮件 --------发件人： Predidit ***@***.***>日期： 2024年7月8日周一 16:09收件人： Predidit/KazumiRules ***@***.***>抄送： humosu ***@***.***>, Author ***@***.***>主    题： Re: [Predidit/KazumiRules] 蜜糖(mitang)，萌番(mengfan)，eacg源无法使用 (Issue #6)
我这边测试都没有问题。
梯子关了试试？这些站点基本都对来自中国之外地区的访问要求验证码。

**Comment by humosu** [comment]
好像是中国移动屏蔽的eacg，很多地方都超时，要么ping1ms，对于山西使用中国移动的用户，eacg是不可用的，剩下的网站的人机验证可能对部分IP才有效，所以导致可用状况不同-------- 原始邮件 --------发件人： Predidit ***@***.***>日期： 2024年7月8日周一 16:09收件人： Predidit/KazumiRules ***@***.***>抄送： humosu ***@***.***>, Author ***@***.***>主    题： Re: [Predidit/KazumiRules] 蜜糖(mitang)，萌番(mengfan)，eacg源无法使用 (Issue #6)
我这边测试都没有问题。
梯子关了试试？这些站点基本都对来自中国之外地区的访问要求验证码。
