### ISSUE TITLE
动漫网站1anime.me自建规则无法使用，能帮忙看一下吗ouo

### ISSUE THREAD

**Issue by wrc-123** [Predidit/KazumiRules#7]
[kazumi   1anime规则.txt](https://github.com/user-attachments/files/16128350/kazumi.1anime.txt)

**Comment by Predidit** [comment]
我大概看了一下，不是 Kazumi 的问题，这个规则写错了。

主要问题在于 SearchResult 对应的应该是番剧详情页面，而不是直接的播放页面。

正确的应该是这样的

https://1anime.me/
https://1anime.me/vodsearch/-------------.html?wd=@keyword
//div[1]/div[2]/div/div/div[2]/div//div
//div[2]/div[1]/a/strong
//div[2]/div[1]/a
//div/div[2]/div/div[2]/div[2]/div/div
//a

有兴趣的话可以向规则仓库提交自己的编写的规则，让这个项目变得更好。

**Comment by wrc-123** [comment]
感谢感谢！ouo

**Comment by oldsento** [comment]
网站挂了诶
