### ISSUE TITLE
不知道为什么网络异常

### ISSUE THREAD

**Issue by ssincxv** [Predidit/KazumiRules#9]
![QQ20240720-120553](https://github.com/user-attachments/assets/a6590160-43ce-4c42-b29a-e9cc7ce0b4f6)
使用的仓库规则，vpn使用的clash verge，全局规则直连都是异常

**Comment by Predidit** [comment]
windows 上的应用程序默认都是不走系统代理的，遵守系统代理设置的一般只有浏览器。

此外不建议开代理使用本程序，代理IP一般使用人数较多，视频源对这种IP一般有限制。

圣母在上第三季比较冷门，可能一些视频源没有收录，这是很正常的。

不建议一次加载过多规则，这不仅会增加视频源的负担，也会浪费本地内存和计算资源。此外只要有任意视频源拉取错误就会出现 连接错误 的提示。过多规则也不利于故障排查。

**Comment by ssincxv** [comment]
![QQ20240720-125148](https://github.com/user-attachments/assets/5d76c756-4599-4c1d-8f1d-6054d41315a7)
重新装了只使用默认规则

**Comment by Predidit** [comment]
不要用代理，这日志是正常的，等一会儿就好了

**Comment by suwutong** [comment]
> 不要用代理，这日志是正常的，等一会儿就好了
大佬大佬，我这个开不开代理都是这个样子，该怎么办

![Image](https://github.com/user-attachments/assets/e1202171-d7c2-4f53-a8ce-4be08758b355)

-

![Image](https://github.com/user-attachments/assets/c1f19056-5ec2-4f5a-9b3e-26d358cc49c4)
